query ($after: String) {
  search(query: "language:Java stars:>1 sort:stars-desc", type: REPOSITORY, first: 20, after: $after) {
    edges {
      node {
        ... on Repository {
          name
          owner {
            login
          }
          stargazerCount
          createdAt
          forkCount
          releases {
            totalCount
          }
          defaultBranchRef {
            target {
              ... on Commit {
                history(first: 1) {
                  nodes {
                    committedDate
                  }
                }
              }
            }
          }
          url
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
